- name: Add key for jonathonf PPA
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 4AB0F789CBA31744CC7DA76A8CF63AD3F06FC659
    state: present
    
- name: Add jonathonf PPA
  apt_repository:
    repo: deb http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial main
    state: present

- name: Install Python3.6 and pip3
  apt:
      name: ['python3.6','python3-pip']
      update_cache: true
      state: present

- name: Install 'virtualenv' package
  pip:
    name: virtualenv
    executable: pip3

- name: install the requirements with pip
  pip: 
    name: ['flask','Werkzeug']
    executable: pip3

- name: Create virtualenv
  become: no
  pip:
    virtualenv: "{{ venv_path }}"
    virtualenv_python: python3.6
    requirements: "{{ requirements_path }}"

- name: create dir for repo as sudo
  file:
    path: /webapps/devops
    state: directory
    owner: vagrant
    group: vagrant
    
- name: change the timezone to UTC
  timezone:
    name: Etc/UTC
  become: yes
  
- name: clone repo
  become: no 
  git:
    repo: 'https://github.com/kparashar/flask_app.git'
    dest: /webapps/devops

- name: Launch flask website
  shell: "cd /webapps/devops; sudo nohup flask run --host 10.10.10.20 --port 80 2>&1 >/dev/null &"
